{{- if .Values.ingress.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-pv-vol1
  labels:
    type: local
spec:
  storageClassName: {{ .Values.volume.storageClassName }} 
  capacity:
    storage: {{ .Values.volume.storage | quote  }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.volume.path }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc-claim
spec:
  storageClassName: {{ .Values.volume.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volume.storage }}
{{- end }}
